package com.example.kernlang.db.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Abstract superclass of the JDBC-DAOs
 */

public class JDBCAbstractDAO {

    private final Connection connection;

    public JDBCAbstractDAO(Connection connection) {
        this.connection = connection;
    }

    /**
     * Helper method to return prep. statements
     * @param sql query
     * @return PreparedStatement
     * @throws SQLException
     */
    protected PreparedStatement prepare (String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    /**
     * Helper method to return prep. statements that also auto generates keys
     * @param sql query
     * @return PreparedStatement with auto generated keys
     * @throws SQLException
     */
    protected PreparedStatement prepareAutoGenerated(String sql) throws SQLException {
        return connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
    }
}
